[options]
colorscheme = "github_dimmed"
colorscheme_bg = "dark"
enable_guicolors = true
custom_color_palette = [
    ["#545d68", "#264466", 246, 235],
    ["#545d68", "#539bf5", 239, 246],
    ["#545d68", "#636e7b", 237, 246],
    ["#22272e", 241],
    ["#545d68", "#83a598", 235, 109],
    ["#545d68", "#fe8019", 235, 208],
    ["#545d68", "#8ec07c", 235, 108],
    ["#545d68", "#689d6a", 235, 72],
    ["#545d68", "#8f3f71", 235, 132],
]

statusline_separator = "arrow"
statusline_inactive_separator = "arrow"
buffer_index_type = 4
enable_tabline_filetype_icon = true
enable_statusline_mode = false
automatic_update = true

filetree_direction = "left"

bootstrap_before = 'custom#before'

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "colorscheme"

[[layers]]
name = "core"
filetree_show_hidden = true

[[layers]]
name = "fzf"

[[layers]]
name = "git"

[[layers]]
name = "github"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#vim"

[[layers]]
name = "treesitter"

[[layers]]
name = "VersionControl"

[[custom_plugins]]
repo = "cuducos/yaml.nvim"

[[custom_plugins]]
repo = "projekt0n/github-nvim-theme"
