# GitHub Dark Dimmed

[colors]
foreground = "#768390"
background = "#1e2228"
cursor_bg = "#768390"
cursor_border = "#768390"
cursor_fg = "#768390"
selection_bg = "#55585e"
selection_fg = "#748391"

ansi = ["#545d68","#f47067","#57ab5a","#c69026","#539bf5","#b083f0","#39c5cf","#909dab"]
brights = ["#636e7b","#ff938a","#6bc46d","#daaa3f","#6cb6ff","#dcbdfb","#56d4dd","#cdd9e5"]
